title: New year, new page
author: Moi, GitHub User
email: dont-spam-me@fake.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
  This is my introduction to my new site.
  Testing new lines and trying out this space.
  See you later!

# social links
twitter_username: does-not-exist-or-i-have-forgotten # DO NOT include the @ character, or else the build will fail!
github_username:  kuoyce # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
